name: Testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "*" ]

jobs:
  BuildSystem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare System
        run: sudo apt-get install -y cmake libgtest-dev g++
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Repository
          path: .
          retention-days: 1
  Tests:
    needs: BuildSystem
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Repository
      - name: Run Tests
        run: mkdir build && cd build && cmake .. && make && ./Tests
