name: Testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "*" ]

jobs:
  Build:
    strategy:
      matrix:
        compiler: ['clang']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Preparing
        run: |
          sudo apt-get update && sudo apt-get install cmake clang libgtest-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
      - name: Build
        run: mkdir build && cd build && cmake .. && make
      - name: Uploading Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: build/Tests
          retention-days: 1
  Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - shell: bash
        run: |
          cd /home/runner/work/Compilers-2024/Compilers-2024/artifact
          chmod +x Tests
          ./Tests