name: Testing

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "*" ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare System
        run: sudo apt-get install -y cmake libgtest-dev g++
      - name: Run Tests
        run: mkdir build && cd build && cmake ../ && make && ./Tests